import { MigrationInterface, QueryRunner } from 'typeorm';

/**
 * Esquema inicial (docs/BASE_DATOS.md). SQL explícito para que cada restricción sea visible:
 * - PK integer en suppliers/depots/cities porque el contrato expone esos ids como integer.
 * - vehicle_models.id = vehicle_id del contrato (modelo comercial "o similar").
 * - EXCLUDE por placa: una unidad física nunca está en dos alquileres activos solapados.
 * - EXCLUDE en rates: no hay dos tarifas vigentes a la vez para el mismo proveedor y categoría.
 * - rental_period / period son columnas generadas a partir de las fechas (no pueden desincronizarse).
 */
export class InitialSchema1790700000000 implements MigrationInterface {
  name = 'InitialSchema1790700000000';

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`CREATE EXTENSION IF NOT EXISTS btree_gist`);
    await queryRunner.query(`CREATE EXTENSION IF NOT EXISTS citext`);

    // ── Enums ────────────────────────────────────────────────────────────────
    await queryRunner.query(`CREATE TYPE user_role AS ENUM ('CUSTOMER', 'ADMIN')`);
    await queryRunner.query(`CREATE TYPE transmission AS ENUM ('MANUAL', 'AUTOMATIC')`);
    await queryRunner.query(`CREATE TYPE fuel_type AS ENUM ('GASOLINE', 'DIESEL', 'HYBRID', 'ELECTRIC')`);
    await queryRunner.query(`CREATE TYPE fuel_policy AS ENUM ('FULL_TO_FULL', 'SAME_TO_SAME', 'PREPAID')`);
    await queryRunner.query(`CREATE TYPE unit_status AS ENUM ('AVAILABLE', 'MAINTENANCE', 'OUT_OF_SERVICE')`);
    await queryRunner.query(`CREATE TYPE order_status AS ENUM ('PENDING', 'CONFIRMED', 'CANCELLED')`);
    await queryRunner.query(`CREATE TYPE rental_status AS ENUM ('NOT_STARTED', 'PICKED_UP', 'RETURNED')`);
    await queryRunner.query(`CREATE TYPE hold_status AS ENUM ('HELD', 'CONSUMED', 'EXPIRED', 'RELEASED')`);
    await queryRunner.query(`CREATE TYPE order_channel AS ENUM ('WEB', 'BOOKING_HUB')`);
    await queryRunner.query(`CREATE TYPE extra_type AS ENUM ('EQUIPMENT', 'COVERAGE', 'SERVICE')`);
    await queryRunner.query(`CREATE TYPE idempotency_status AS ENUM ('IN_PROGRESS', 'COMPLETED')`);
    await queryRunner.query(`CREATE TYPE delivery_status AS ENUM ('PENDING', 'SUCCEEDED', 'FAILED', 'DEAD')`);

    // ── Usuarios ─────────────────────────────────────────────────────────────
    await queryRunner.query(`
      CREATE TABLE users (
        id            uuid PRIMARY KEY DEFAULT gen_random_uuid(),
        email         citext NOT NULL UNIQUE,
        password_hash varchar(100) NOT NULL,
        first_name    varchar(60) NOT NULL,
        last_name     varchar(60) NOT NULL,
        phone         varchar(20),
        role          user_role NOT NULL DEFAULT 'CUSTOMER',
        active        boolean NOT NULL DEFAULT true,
        created_at    timestamptz NOT NULL DEFAULT now(),
        updated_at    timestamptz NOT NULL DEFAULT now()
      )`);

    // ── Catálogo ─────────────────────────────────────────────────────────────
    await queryRunner.query(`
      CREATE TABLE cities (
        id           integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        name         varchar(80) NOT NULL,
        country_code char(2) NOT NULL CHECK (country_code ~ '^[a-z]{2}$'),
        UNIQUE (name, country_code)
      )`);

    await queryRunner.query(`
      CREATE TABLE suppliers (
        id         integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        code       varchar(10) NOT NULL UNIQUE,
        name       varchar(100) NOT NULL,
        logo_url   text,
        active     boolean NOT NULL DEFAULT true,
        created_at timestamptz NOT NULL DEFAULT now(),
        updated_at timestamptz NOT NULL DEFAULT now()
      )`);

    await queryRunner.query(`
      CREATE TABLE depots (
        id           integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        supplier_id  integer NOT NULL REFERENCES suppliers(id),
        city_id      integer NOT NULL REFERENCES cities(id),
        name         varchar(120) NOT NULL,
        address      varchar(200) NOT NULL,
        airport_code char(3) CHECK (airport_code ~ '^[A-Z]{3}$'),
        latitude     numeric(9,6) NOT NULL CHECK (latitude BETWEEN -90 AND 90),
        longitude    numeric(9,6) NOT NULL CHECK (longitude BETWEEN -180 AND 180),
        timezone     varchar(50) NOT NULL DEFAULT 'America/Guayaquil',
        phone        varchar(20),
        services     text[] NOT NULL DEFAULT '{}',
        active       boolean NOT NULL DEFAULT true,
        created_at   timestamptz NOT NULL DEFAULT now(),
        updated_at   timestamptz NOT NULL DEFAULT now()
      )`);
    await queryRunner.query(`CREATE INDEX idx_depots_airport ON depots (airport_code)`);
    await queryRunner.query(`CREATE INDEX idx_depots_city ON depots (city_id)`);
    await queryRunner.query(`CREATE INDEX idx_depots_updated ON depots (updated_at)`);

    await queryRunner.query(`
      CREATE TABLE depot_opening_hours (
        depot_id integer NOT NULL REFERENCES depots(id) ON DELETE CASCADE,
        weekday  smallint NOT NULL CHECK (weekday BETWEEN 0 AND 6),
        opens    time NOT NULL,
        closes   time NOT NULL,
        PRIMARY KEY (depot_id, weekday),
        CHECK (opens < closes)
      )`);

    await queryRunner.query(`
      CREATE TABLE vehicle_categories (
        id             uuid PRIMARY KEY DEFAULT gen_random_uuid(),
        code           varchar(20) NOT NULL UNIQUE,
        name           varchar(60) NOT NULL,
        description    text,
        min_driver_age smallint NOT NULL CHECK (min_driver_age BETWEEN 18 AND 99),
        sort_order     smallint NOT NULL DEFAULT 0
      )`);

    await queryRunner.query(`
      CREATE TABLE vehicle_models (
        id               uuid PRIMARY KEY DEFAULT gen_random_uuid(),
        supplier_id      integer NOT NULL REFERENCES suppliers(id),
        category_id      uuid NOT NULL REFERENCES vehicle_categories(id),
        make             varchar(50) NOT NULL,
        model            varchar(60) NOT NULL,
        acriss_code      char(4),
        transmission     transmission NOT NULL,
        fuel_type        fuel_type NOT NULL,
        fuel_policy      fuel_policy NOT NULL DEFAULT 'FULL_TO_FULL',
        seats            smallint NOT NULL CHECK (seats > 0),
        doors            smallint NOT NULL CHECK (doors > 0),
        bag_capacity     smallint NOT NULL CHECK (bag_capacity >= 0),
        air_conditioning boolean NOT NULL DEFAULT true,
        image_url        text,
        description      text,
        published        boolean NOT NULL DEFAULT false,
        active           boolean NOT NULL DEFAULT true,
        created_at       timestamptz NOT NULL DEFAULT now(),
        updated_at       timestamptz NOT NULL DEFAULT now()
      )`);
    await queryRunner.query(`CREATE INDEX idx_vehicle_models_supplier_category ON vehicle_models (supplier_id, category_id)`);
    await queryRunner.query(`CREATE INDEX idx_vehicle_models_updated ON vehicle_models (updated_at)`);

    await queryRunner.query(`
      CREATE TABLE fleet_units (
        id               uuid PRIMARY KEY DEFAULT gen_random_uuid(),
        vehicle_model_id uuid NOT NULL REFERENCES vehicle_models(id),
        depot_id         integer NOT NULL REFERENCES depots(id),
        plate            varchar(10) NOT NULL UNIQUE,
        year             smallint NOT NULL CHECK (year BETWEEN 1990 AND 2100),
        color            varchar(30),
        mileage          integer NOT NULL DEFAULT 0 CHECK (mileage >= 0),
        status           unit_status NOT NULL DEFAULT 'AVAILABLE',
        active           boolean NOT NULL DEFAULT true,
        created_at       timestamptz NOT NULL DEFAULT now(),
        updated_at       timestamptz NOT NULL DEFAULT now()
      )`);
    await queryRunner.query(`CREATE INDEX idx_fleet_units_model_depot ON fleet_units (vehicle_model_id, depot_id)`);

    await queryRunner.query(`
      CREATE TABLE vehicle_blocks (
        id            uuid PRIMARY KEY DEFAULT gen_random_uuid(),
        fleet_unit_id uuid NOT NULL REFERENCES fleet_units(id) ON DELETE CASCADE,
        starts_at     timestamptz NOT NULL,
        ends_at       timestamptz NOT NULL,
        period        tstzrange GENERATED ALWAYS AS (tstzrange(starts_at, ends_at, '[)')) STORED,
        reason        varchar(200) NOT NULL,
        created_by    uuid REFERENCES users(id),
        created_at    timestamptz NOT NULL DEFAULT now(),
        CHECK (starts_at < ends_at)
      )`);
    await queryRunner.query(`CREATE INDEX idx_vehicle_blocks_unit_period ON vehicle_blocks USING gist (fleet_unit_id, period)`);

    await queryRunner.query(`
      CREATE TABLE rates (
        id          uuid PRIMARY KEY DEFAULT gen_random_uuid(),
        supplier_id integer NOT NULL REFERENCES suppliers(id),
        category_id uuid NOT NULL REFERENCES vehicle_categories(id),
        daily_rate  numeric(12,2) NOT NULL CHECK (daily_rate > 0),
        currency    char(3) NOT NULL DEFAULT 'USD',
        valid_from  date NOT NULL,
        valid_to    date NOT NULL,
        created_at  timestamptz NOT NULL DEFAULT now(),
        updated_at  timestamptz NOT NULL DEFAULT now(),
        CHECK (valid_from <= valid_to),
        CONSTRAINT rates_no_overlap EXCLUDE USING gist (
          supplier_id WITH =, category_id WITH =, daterange(valid_from, valid_to, '[]') WITH &&
        )
      )`);

    await queryRunner.query(`
      CREATE TABLE extras (
        id            uuid PRIMARY KEY DEFAULT gen_random_uuid(),
        code          varchar(30) NOT NULL UNIQUE,
        name          varchar(80) NOT NULL,
        description   text,
        type          extra_type NOT NULL,
        price_per_day numeric(12,2) NOT NULL CHECK (price_per_day >= 0),
        max_price     numeric(12,2) CHECK (max_price IS NULL OR max_price >= 0),
        active        boolean NOT NULL DEFAULT true,
        created_at    timestamptz NOT NULL DEFAULT now(),
        updated_at    timestamptz NOT NULL DEFAULT now()
      )`);

    await queryRunner.query(`
      CREATE TABLE currency_rates (
        currency      char(3) PRIMARY KEY CHECK (currency ~ '^[A-Z]{3}$'),
        rate_from_usd numeric(14,6) NOT NULL CHECK (rate_from_usd > 0),
        updated_at    timestamptz NOT NULL DEFAULT now()
      )`);

    // ── Integración ──────────────────────────────────────────────────────────
    await queryRunner.query(`
      CREATE TABLE affiliates (
        id                 integer PRIMARY KEY,
        name               varchar(100) NOT NULL,
        commission_rate    numeric(5,4) NOT NULL DEFAULT 0 CHECK (commission_rate BETWEEN 0 AND 1),
        rate_limit_per_min integer NOT NULL DEFAULT 120 CHECK (rate_limit_per_min > 0),
        active             boolean NOT NULL DEFAULT true,
        created_at         timestamptz NOT NULL DEFAULT now()
      )`);

    await queryRunner.query(`
      CREATE TABLE api_clients (
        client_id          varchar(64) PRIMARY KEY,
        client_secret_hash varchar(100) NOT NULL,
        name               varchar(100) NOT NULL,
        scopes             text[] NOT NULL DEFAULT '{}',
        affiliate_id       integer REFERENCES affiliates(id),
        active             boolean NOT NULL DEFAULT true,
        created_at         timestamptz NOT NULL DEFAULT now()
      )`);

    // ── Flujo de reserva ─────────────────────────────────────────────────────
    await queryRunner.query(`
      CREATE TABLE search_sessions (
        id                uuid PRIMARY KEY DEFAULT gen_random_uuid(),
        channel           order_channel NOT NULL,
        owner_sub         varchar(200),
        affiliate_id      integer,
        pickup_at         timestamptz NOT NULL,
        dropoff_at        timestamptz NOT NULL,
        pickup_depot_ids  integer[] NOT NULL,
        dropoff_depot_ids integer[] NOT NULL,
        driver_age        smallint NOT NULL,
        booker_country    char(2) NOT NULL,
        currency          char(3) NOT NULL,
        request           jsonb NOT NULL,
        results           jsonb NOT NULL DEFAULT '[]',
        created_at        timestamptz NOT NULL DEFAULT now(),
        expires_at        timestamptz NOT NULL
      )`);
    await queryRunner.query(`CREATE INDEX idx_search_sessions_expires ON search_sessions (expires_at)`);

    await queryRunner.query(`
      CREATE TABLE holds (
        id                uuid PRIMARY KEY DEFAULT gen_random_uuid(),
        search_session_id uuid NOT NULL REFERENCES search_sessions(id),
        vehicle_model_id  uuid NOT NULL REFERENCES vehicle_models(id),
        pickup_depot_id   integer NOT NULL REFERENCES depots(id),
        dropoff_depot_id  integer NOT NULL REFERENCES depots(id),
        owner_sub         varchar(200) NOT NULL,
        pickup_at         timestamptz NOT NULL,
        dropoff_at        timestamptz NOT NULL,
        period            tstzrange GENERATED ALWAYS AS (tstzrange(pickup_at, dropoff_at, '[)')) STORED,
        quoted_total      numeric(12,2) NOT NULL,
        currency          char(3) NOT NULL,
        status            hold_status NOT NULL DEFAULT 'HELD',
        expires_at        timestamptz NOT NULL,
        created_at        timestamptz NOT NULL DEFAULT now()
      )`);
    await queryRunner.query(`CREATE INDEX idx_holds_active ON holds (vehicle_model_id, pickup_depot_id) WHERE status = 'HELD'`);

    await queryRunner.query(`
      CREATE TABLE order_previews (
        id                uuid PRIMARY KEY DEFAULT gen_random_uuid(),
        search_session_id uuid NOT NULL REFERENCES search_sessions(id),
        hold_id           uuid REFERENCES holds(id),
        vehicle_model_id  uuid NOT NULL REFERENCES vehicle_models(id),
        pickup_depot_id   integer NOT NULL REFERENCES depots(id),
        dropoff_depot_id  integer NOT NULL REFERENCES depots(id),
        owner_sub         varchar(200) NOT NULL,
        extras            jsonb NOT NULL DEFAULT '[]',
        breakdown         jsonb NOT NULL,
        total_price       numeric(12,2) NOT NULL,
        currency          char(3) NOT NULL,
        expires_at        timestamptz NOT NULL,
        consumed_at       timestamptz,
        created_at        timestamptz NOT NULL DEFAULT now()
      )`);

    await queryRunner.query(`
      CREATE TABLE reservations (
        id                uuid PRIMARY KEY DEFAULT gen_random_uuid(),
        locator           varchar(20) NOT NULL UNIQUE,
        status            order_status NOT NULL DEFAULT 'CONFIRMED',
        rental_status     rental_status NOT NULL DEFAULT 'NOT_STARTED',
        channel           order_channel NOT NULL,
        owner_sub         varchar(200) NOT NULL,
        user_id           uuid REFERENCES users(id),
        affiliate_id      integer,
        vehicle_model_id  uuid NOT NULL REFERENCES vehicle_models(id),
        fleet_unit_id     uuid REFERENCES fleet_units(id),
        pickup_depot_id   integer NOT NULL REFERENCES depots(id),
        dropoff_depot_id  integer NOT NULL REFERENCES depots(id),
        pickup_at         timestamptz NOT NULL,
        dropoff_at        timestamptz NOT NULL,
        rental_period     tstzrange GENERATED ALWAYS AS (tstzrange(pickup_at, dropoff_at, '[)')) STORED,
        driver_first_name varchar(60) NOT NULL,
        driver_last_name  varchar(60) NOT NULL,
        driver_email      varchar(120) NOT NULL,
        driver_phone      varchar(30),
        driver_age        smallint NOT NULL CHECK (driver_age BETWEEN 18 AND 99),
        booker_country    char(2) NOT NULL,
        vehicle_snapshot  jsonb NOT NULL,
        route_snapshot    jsonb NOT NULL,
        price_breakdown   jsonb NOT NULL,
        total_price       numeric(12,2) NOT NULL CHECK (total_price >= 0),
        currency          char(3) NOT NULL,
        payment_reference varchar(64) NOT NULL,
        order_preview_id  uuid UNIQUE REFERENCES order_previews(id),
        hold_id           uuid REFERENCES holds(id),
        cancelled_at      timestamptz,
        cancellation_fee  numeric(12,2),
        version           integer NOT NULL DEFAULT 1,
        created_at        timestamptz NOT NULL DEFAULT now(),
        updated_at        timestamptz NOT NULL DEFAULT now(),
        CHECK (pickup_at < dropoff_at),
        CONSTRAINT reservations_unit_no_overlap EXCLUDE USING gist (
          fleet_unit_id WITH =, rental_period WITH &&
        ) WHERE (fleet_unit_id IS NOT NULL AND status IN ('PENDING', 'CONFIRMED'))
      )`);
    await queryRunner.query(`CREATE INDEX idx_reservations_owner ON reservations (owner_sub, created_at DESC)`);
    await queryRunner.query(`CREATE INDEX idx_reservations_inventory ON reservations (vehicle_model_id, pickup_depot_id, status)`);
    await queryRunner.query(`CREATE INDEX idx_reservations_status_pickup ON reservations (status, pickup_at)`);

    await queryRunner.query(`
      CREATE TABLE reservation_extras (
        reservation_id uuid NOT NULL REFERENCES reservations(id) ON DELETE CASCADE,
        extra_id       uuid NOT NULL REFERENCES extras(id),
        code           varchar(30) NOT NULL,
        name           varchar(80) NOT NULL,
        unit_price     numeric(12,2) NOT NULL,
        days           smallint NOT NULL,
        subtotal       numeric(12,2) NOT NULL,
        PRIMARY KEY (reservation_id, extra_id)
      )`);

    await queryRunner.query(`
      CREATE TABLE reservation_history (
        id             uuid PRIMARY KEY DEFAULT gen_random_uuid(),
        reservation_id uuid NOT NULL REFERENCES reservations(id) ON DELETE CASCADE,
        action         varchar(30) NOT NULL,
        actor_sub      varchar(200) NOT NULL,
        before         jsonb,
        after          jsonb,
        created_at     timestamptz NOT NULL DEFAULT now()
      )`);
    await queryRunner.query(`CREATE INDEX idx_reservation_history_reservation ON reservation_history (reservation_id)`);

    await queryRunner.query(`
      CREATE TABLE depot_reviews (
        id             uuid PRIMARY KEY DEFAULT gen_random_uuid(),
        depot_id       integer NOT NULL REFERENCES depots(id),
        reservation_id uuid UNIQUE REFERENCES reservations(id),
        user_id        uuid REFERENCES users(id),
        score          smallint NOT NULL CHECK (score BETWEEN 1 AND 10),
        comment        text,
        created_at     timestamptz NOT NULL DEFAULT now()
      )`);
    await queryRunner.query(`CREATE INDEX idx_depot_reviews_depot ON depot_reviews (depot_id)`);

    // ── Idempotencia y eventos ───────────────────────────────────────────────
    await queryRunner.query(`
      CREATE TABLE idempotency_records (
        owner_sub       varchar(200) NOT NULL,
        idempotency_key uuid NOT NULL,
        operation       varchar(60) NOT NULL,
        request_hash    char(64) NOT NULL,
        status          idempotency_status NOT NULL,
        response_status smallint,
        response_body   jsonb,
        created_at      timestamptz NOT NULL DEFAULT now(),
        expires_at      timestamptz NOT NULL,
        PRIMARY KEY (owner_sub, idempotency_key, operation)
      )`);
    await queryRunner.query(`CREATE INDEX idx_idempotency_expires ON idempotency_records (expires_at)`);

    await queryRunner.query(`
      CREATE TABLE outbox_events (
        id            uuid PRIMARY KEY DEFAULT gen_random_uuid(),
        event_type    varchar(60) NOT NULL,
        resource_id   varchar(100) NOT NULL,
        payload       jsonb NOT NULL,
        occurred_at   timestamptz NOT NULL DEFAULT now(),
        dispatched_at timestamptz
      )`);
    await queryRunner.query(`CREATE INDEX idx_outbox_pending ON outbox_events (occurred_at) WHERE dispatched_at IS NULL`);

    await queryRunner.query(`
      CREATE TABLE webhook_subscriptions (
        id               uuid PRIMARY KEY,
        owner_sub        varchar(200) NOT NULL,
        url              text NOT NULL,
        events           text[] NOT NULL,
        secret_encrypted text,
        active           boolean NOT NULL DEFAULT true,
        created_at       timestamptz NOT NULL DEFAULT now()
      )`);

    await queryRunner.query(`
      CREATE TABLE webhook_deliveries (
        id              uuid PRIMARY KEY DEFAULT gen_random_uuid(),
        event_id        uuid NOT NULL REFERENCES outbox_events(id),
        subscription_id uuid NOT NULL REFERENCES webhook_subscriptions(id) ON DELETE CASCADE,
        attempt         smallint NOT NULL DEFAULT 0,
        status          delivery_status NOT NULL DEFAULT 'PENDING',
        response_code   smallint,
        last_error      text,
        next_attempt_at timestamptz NOT NULL DEFAULT now(),
        delivered_at    timestamptz,
        created_at      timestamptz NOT NULL DEFAULT now(),
        UNIQUE (event_id, subscription_id)
      )`);
    await queryRunner.query(`CREATE INDEX idx_webhook_deliveries_due ON webhook_deliveries (status, next_attempt_at)`);
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    const tables = [
      'webhook_deliveries', 'webhook_subscriptions', 'outbox_events', 'idempotency_records',
      'depot_reviews', 'reservation_history', 'reservation_extras', 'reservations', 'order_previews',
      'holds', 'search_sessions', 'api_clients', 'affiliates', 'currency_rates', 'extras', 'rates',
      'vehicle_blocks', 'fleet_units', 'vehicle_models', 'vehicle_categories', 'depot_opening_hours',
      'depots', 'suppliers', 'cities', 'users',
    ];
    for (const table of tables) await queryRunner.query(`DROP TABLE IF EXISTS ${table}`);

    const types = [
      'delivery_status', 'idempotency_status', 'extra_type', 'order_channel', 'hold_status', 'rental_status',
      'order_status', 'unit_status', 'fuel_policy', 'fuel_type', 'transmission', 'user_role',
    ];
    for (const type of types) await queryRunner.query(`DROP TYPE IF EXISTS ${type}`);
  }
}
